#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color "#ba85cc"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
xrandr -s 1600x900
${HOME}/.fehbg
compton &
bash .config/polybar/launch.sh --shapes
/home/thaylor/Applications/Notion-Enhanced-2.0.18-1_d1a79463ea5ee795379f09327fbee756.AppImage --no-sandbox %U
thunderbird
